name: build-release-crossplatform

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release-crossplatform:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Ensure `cargo fmt` was run
      run: cargo fmt --check
    - name: Ensure `cargo clippy` is satisfied
      run: cargo clippy
    - name: Test
      run: cargo test --profile small
    - name: Build
      run: cargo build --profile small
    - name: Archive release artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: target/small/xkcd-password-gen
